# (C) Copyright 2024 ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

name: Build Linux

on:
  # Trigger the workflow manually
  workflow_dispatch: ~

  release:
    types: [created]

  # repository_dispatch:
  #   types: [eccodes-updated]

  push:
    paths:
    - 'scripts/common.sh'
    - 'scripts/select-python.sh'
    - 'scripts/build-macos.sh'
    - 'scripts/wheel-macos.sh'
    - 'scripts/test-macos.sh'
    - 'scripts/build-linux.sh'
    - '.github/workflows/build-wheel-macos-arm.yml'
    - '.github/workflows/build-wheel-linux.yml'
    #- 'tools/copy-licences.py'


jobs:

  build:

    # if: false

    runs-on: [self-hosted, Linux, platform-builder-Rocky-8.6]
    container: dockcross/manylinux2014-x64:latest

    name: Build manylinux2014

    steps:
      - uses: actions/checkout@v2

      - run: ./scripts/build-linux.sh

      ################################################################
      - run: ./scripts/wheel-linux.sh 3.8
      - uses: actions/upload-artifact@v2
        name: Upload wheel 3.8
        with:
          name: wheel-manylinux2014-3.8
          path: wheelhouse/*.whl
