# (C) Copyright 2024- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.


name: Build Python Wheel for Linux

on:
  # Trigger the workflow manually
  workflow_dispatch:
    inputs:
      use_test_pypi:
        description: Use test pypi instead of the regular one
        required: false
        type: boolean
        default: false

  # Allow to be called from another workflow -- eg `cd.yml`
  workflow_call:
    inputs:
      use_test_pypi:
        description: Use test pypi instead of the regular one
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build manylinux_2_28
    strategy:
      fail-fast: true
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: [self-hosted, Linux, platform-builder-Rocky-8.6]
    container:
      image: eccr.ecmwf.int/wheelmaker/2_28:1.latest
      credentials:
        username: ${{ secrets.ECMWF_DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.ECMWF_DOCKER_REGISTRY_ACCESS_TOKEN }}
    steps:
      - run: |
          set -euo pipefail
          git clone --depth=1 --branch="${GITHUB_REF#refs/heads/}" https://github.com/$GITHUB_REPOSITORY /src/eccodes-python
          cd /src/eccodes-python
          if [ "$GITHUB_REF_NAME" != "main" -a "$GITHUB_REF_NAME" != "master" -a "$GITHUB_REF_TYPE" != "tag" ] ; then
            export UV_CACHE_DIR="/tmp/reallynocache"
            rm -rf $UV_CACHE_DIR && mkdir $UV_CACHE_DIR
            EXTRA_PIP="--refresh --no-cache --prerelease=allow"
          else
            EXTRA_PIP=""
          fi

          VENV_ROOT=/venv/build"${{ matrix.python_version }}"
          source $VENV_ROOT/bin/activate
          uv pip install $EXTRA_PIP eccodeslib
          EL_ROOT=$VENV_ROOT/lib/python"${{ matrix.python_version }}"/site-packages/eccodeslib
          export LIBDIR=$EL_ROOT/lib64
          export INCDIR=$EL_ROOT/include
          python -m build --no-isolation .

          uv pip install $EXTRA_PIP ./dist/*whl pytest
          cd tests
          ECCODES_PYTHON_TRACE_LIB_SEARCH=1 pytest -v -s
          cd ..

          if [ "${{ inputs.use_test_pypi }}" = "true" ] ; then UPLOAD_TO=test ; else UPLOAD_TO=prod ; fi
          PYTHONPATH=/buildscripts /buildscripts/upload-pypi.sh $UPLOAD_TO ./dist
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD_PROD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_PASSWORD_TEST: ${{ secrets.PYPI_TEST_API_TOKEN }}
