# (C) Copyright 2024- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

name: cd

on:
  # Trigger the workflow manually
  workflow_dispatch: ~

  push:
    tags:
      - '**'
    paths:
      - '.github/workflows/cd.yml'
jobs:
  wheel-windows:
    uses: ./.github/workflows/build-wheel-windows.yml
    secrets: inherit
  pypi:
    needs: [wheel-windows]
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@v2
    with:
      env_vars: |
        {
          "DEPEND_ON_ECCODESLIB": "1"
        }
      buildargs: --no-isolation
    secrets: inherit
    

