name: ci

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  # Trigger the workflow on pull request
  pull_request: ~

  # Trigger the workflow manually
  workflow_dispatch: ~

  # Trigger after public PR approved for CI
  pull_request_target:
    types: [labeled]

jobs:
  # Run CI including downstream packages on self-hosted runners
  downstream-ci:
    name: downstream-ci
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}
    uses: ecmwf-actions/downstream-ci/.github/workflows/downstream-ci.yml@main
    with:
      eccodes-python: ecmwf/eccodes-python@${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit

  # Build and test this packcage on HPC
  ci-hpc:
    name: ci-hpc
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}
    uses: ./.github/workflows/reusable-ci-hpc.yml
    with:
      eccodes-python: ecmwf/eccodes-python@${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit
